# Usar una imagen base de Python
FROM python:3.10-slim  

# Establecer el directorio de trabajo en el contenedor
WORKDIR /Proyecto_practica

# Copiar el resto de la aplicación al contenedor
COPY . /Proyecto_practica

# Comando por defecto para ejecutar la aplicación
CMD ["python", "main.py"]